version: '3.8'

services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: PostgresDB
    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet-radar

    volumes:
      - postgresdb_data:/var/lib/postgresql/data

volumes:
  postgresdb_data: